// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvctask1.Data;

#nullable disable

namespace mvctask1.Migrations
{
    [DbContext(typeof(ITIdata))]
    [Migration("20240902210123_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mvctask1.Models.Department", b =>
                {
                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<string>("department_name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Department_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("mvctask1.Models.Student", b =>
                {
                    b.Property<int>("Student_id")
                        .HasColumnType("int");

                    b.Property<int?>("Department_Id")
                        .HasColumnType("int");

                    b.Property<int>("student_age")
                        .HasColumnType("int");

                    b.Property<string>("student_name")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Student_id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("mvctask1.Models.Student", b =>
                {
                    b.HasOne("mvctask1.Models.Department", null)
                        .WithMany("Students")
                        .HasForeignKey("Department_Id");
                });

            modelBuilder.Entity("mvctask1.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
